# Generated by Django 3.1.3 on 2020-11-26 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='course.course'),
        ),
        migrations.AlterField(
            model_name='lessonnode',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='course.lesson'),
        ),
        migrations.AlterField(
            model_name='lessonnodeimage',
            name='lesson_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='course.lessonnode'),
        ),
    ]
